### ISSUE TITLE
Missing delta tmp file 

### ISSUE THREAD

**Issue by kreopelle** [pat/ts-sidekiq-delta#12]
The following error is occurring in an application's production environment: 

```
Errno::ENOENTThinkingSphinx::Deltas::SidekiqDelta::DeltaJob@ts_delta
No such file or directory @ rb_sysopen -  /home/deploy/apps/APPNAME/shared/db/sphinx/production/ts-user_delta.tmp
```

I've rebuilt the indices and have the delta columns and indexes in the database. 

The `indices_location` set in the `thinking_sphinx.yml` file is `/home/deploy/apps/APPNAME/shared/db/sphinx`. 

At that path, I have files like these:
```
user_delta.spa
user_delta.spd
user_delta.spe
user_delta.sph
user_delta.spi
user_delta.spk
user_delta.spl
user_delta.spm
user_delta.spp
user_delta.sps
```

Any suggestions on changes I could make/things I could look into to resolve this error?

**Comment by pat** [comment]
So, the file that it's complaining about is something created by Thinking Sphinx to avoid concurrent processing of the same indices. Having that file not exist is okay, I would think… but maybe there's a race condition with parallel sidekiq jobs. Does the error happen on every job, or only occasionally? And which versions of thinking-sphinx and ts-sidekiq-delta are you using in your app?

**Comment by kreopelle** [comment]
@pat - Thanks for clarifying! We found a Sidekiq process on one of the servers that should not have been there (we started it for testing purposes and then forgot to spin it down), and that's where the error was being triggered. We stopped that process and haven't seen the error since.
