### ISSUE TITLE
Jobs sitting in enqueued

### ISSUE THREAD

**Issue by Justin-Mitchell** [pat/ts-sidekiq-delta#5]
After I save a record, it adds a new job into the ts_delta queue. The queue is building up, and not running through them. I saw in the README that I need to monitor the `ts_delta` queue, but I don't understand what that means. I'm assuming I need some worker that has `sidekiq_options :queue => :ts_delta`, but what would I put in that worker?

**Comment by casiodk** [comment]
I´m having the same issue here. I have a sidekiq.yml file like this

```
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 3
:queues:
  - [default, 1]
  - [mailers, 12]
  - [import, 5]
  - [ts_delta, 1]
  - [map_bbr_data_to_building, 20]
  - [touch_family_later, 2]

```

![screen shot 2016-10-27 at 04 03 34](https://cloud.githubusercontent.com/assets/632607/19752250/3430442c-9bfc-11e6-9772-a8dbe5988a91.png)

**Comment by casiodk** [comment]
Tried to change the Procfile, same problem. Except the other queue is now working

```
worker: bundle exec sidekiq -c 10 -q default,2 -q import,10
workerdelta: bundle exec sidekiq -c 10 -q ts_delta

```


![screen shot 2016-10-27 at 04 19 32](https://cloud.githubusercontent.com/assets/632607/19752309/a7dba39e-9bfc-11e6-82ba-121e91b911c2.png)

**Comment by casiodk** [comment]
Out of 10 processes, seems like only 1 is working - and its really slow

![](https://d3vv6lp55qjaqc.cloudfront.net/items/2q3S2L3o0r0g3b320k2e/Screen%20Recording%202016-10-27%20at%2001.38%20PM.gif?X-CloudApp-Visitor-Id=e672eacc359af3141d507ec7aefbedaa&v=bf585156)

**Comment by pat** [comment]
Hi @casiodk - I'm guessing this is related to a ticket lodged with Heroku and Flying Sphinx (which is now assigned to me)? :)

Can you let me know which versions of the flying-sphinx and thinking-sphinx gems you're using?

**Comment by casiodk** [comment]
yes :)
I´ll answer there

Thanks a lot

**Comment by pat** [comment]
To fix the issue that @casiodk has raised: Thinking Sphinx wasn't defaulting to quiet delta output, which in turn was slowing Flying Sphinx down. TS now defaults to quiet deltas: pat/thinking-sphinx@7d97a98c3562eb970351ad8e24312f266a523769.
