### ISSUE TITLE
ThinkingSphinx::Deltas.suspend! has no effect

### ISSUE THREAD

**Issue by mubashirkamran** [pat/ts-sidekiq-delta#8]
I run ThinkingSphinx::Deltas.suspend! before updating some records. However, the deltas still get fetched by sidekiq and processed.

**Comment by pat** [comment]
I've just tested this locally, and I'm not seeing jobs added to Sidekiq after I call `ThinkingSphinx::Deltas.suspend!` and then add/modify an indexed object.

Can you let me know which versions of Thinking Sphinx, Sidekiq, and Rails you're using? Also, if you can share the code where you're calling `suspend!` and then updating records, that'd be great :)

**Comment by pat** [comment]
Oh, also: which version of ts-sidekiq-delta are you using?

**Comment by pat** [comment]
Closing this issue as it's been dormant for over a month - but certainly, if it's still a problem, or there are other questions/issues, do comment! :)
