### ISSUE TITLE
Apartment gem with multi tenancy

### ISSUE THREAD

**Issue by bkd** [pat/ts-sidekiq-delta#9]
I've just discovered that although using Apartment + TS + Sidekiq Delta for over 3 years, that it actually fires off the job for each tenant whenever the ThinkingSphinx::Deltas::SidekiqDelta::DeltaJob is run.  So any update to any record in any tenant schema will produce a ThinkingSphinx::Deltas::SidekiqDelta::DeltaJob for every core and delta of that model for every tenant.

Pat, I'm sorry to have to ask your guidance again - how can we solve this?

**Comment by pat** [comment]
No need to apologise! Please do keep asking questions - I may not always respond promptly, but I'm glad people are still using the gem, and I'm happy to answer questions and provide support.

A solution for this, I think, is to create your own custom IndexSet class. Here's an example with Apartment in mind: https://gist.github.com/pat/971307984434f564bb50 - you'll see that the IndexSet is only filtering for `core` indices, and you'll want to change that to handle both `core` and `delta` indices.

The IndexSet class is what's used to filter all indices to just relevant ones (i.e. by model or index name) when conducting searches and processing delta indices. If you filter by the current tenant, this should only fire off delta jobs for the actually-relevant indices.

**Comment by bkd** [comment]
Awesome Pat, thanks for that.  Thats done the trick! Once again, very happy that you are very responsive and helpful! ;-)

**Comment by pat** [comment]
Great to hear it's working :)
